// ERRORS FROM BUSINESS LOGIC

exports.ERROR_REQUIRED_FIELD          = "BL2021";
exports.ID_NOT_FOUND                  = "BL2022";
exports.FAIL_CONVERTED_UUID_TO_STRING = "BL2023";
exports.NO_CONTENT                    = "BL2024";
exports.CRASH_LOGIC                   = "BL2025";

//COLORS TO SHOW DETAIL IN LOGS
exports.BLACK_LOG                     = "\x1b[30m%s\x1b[0m";
exports.RED_LOG                       = "\x1b[31m%s\x1b[0m";
exports.GREEN_LOG                     = "\x1b[32m%s\x1b[0m";
exports.YELLOW_LOG                    = "\x1b[33m%s\x1b[0m";
exports.BLUE_LOG                      = "\x1b[34m%s\x1b[0m";
exports.MAGENTA_LOG                   = "\x1b[35m%s\x1b[0m";
exports.CYAN_LOG                      = "\x1b[36m%s\x1b[0m";
exports.WHITE_LOG                     = "\x1b[37m%s\x1b[0m";

// CODE STATUS
exports.CODE_CONTINUE = 100;
exports.CODE_SWITCHING_PROTOCOLS = 101;
exports.CODE_PROCESSING = 102;
exports.CODE_EARLYHINTS = 103;
exports.CODE_OK = 200;
exports.CODE_CREATED = 201;
exports.CODE_ACCEPTED = 202;
exports.CODE_NO_AUTHORITATIVE = 203;
exports.CODE_NO_CONTENT = 204;
exports.CODE_RESET_CONTENT = 205;
exports.CODE_PARTIAL_CONTENT = 206;
exports.CODE_MULTI_STATUS = 207;
exports.CODE_ALREDY_REPORTED = 208;
exports.CODE_IM_USED = 226;
exports.CODE_MULTIPLE_CHOICES = 300;
exports.CODE_MOVED_PERMANENTLY = 301;
exports.CODE_FOUND = 302;
exports.CODE_SEE_OTHER = 303;
exports.CODE_NOT_MODIFIED = 304;
exports.CODE_USE_PROXY = 305;
exports.CODE_SWITCH_PROXY = 306;
exports.CODE_TEMPORARY_REDIRECT = 307;
exports.CODE_PERMANENT_REDIRECT = 308;
exports.CODE_BAD_REQUEST = 400;
exports.CODE_UNAUTHORIZED = 401;
exports.CODE_PAYMENT_REQUIRED = 402;
exports.CODE_FORBIDDEN = 403;
exports.CODE_NOT_FOUND = 404;
exports.CODE_METHOD_NOT_ALLOWED = 405;
exports.CODE_NOT_ACEPTABLE = 406;
exports.CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
exports.CODE_REQUEST_TIMEOUT = 408;
exports.CODE_CONFLICT = 409;
exports.CODE_GONE = 410;
exports.CODE_LENGTH_REQUIRED = 411;
exports.CODE_PRECONDITION_FAILED = 412;
exports.CODE_PAYLOAD_TOO_LARGE = 413;
exports.CODE_URI_TOO_LONG = 414;
exports.CODE_UNSUPPORTED_MEDIA_TYPE = 415;
exports.CODE_RANGE_NOT_SATISFIABLE = 416;
exports.CODE_EXPECTATION_FAILED = 417;
exports.CODE_IAM_A_TEAPOT = 418;
exports.CODE_MISDIRECTED_REQUEST = 421;
exports.CODE_UNPROCESSABLE_ENTITY = 422;
exports.CODE_LOCKED = 423;
exports.CODE_FAILED_DEPENDENCY = 424;
exports.CODE_TOO_EARLY = 425;
exports.CODE_UPGRADE_REQUIERED = 426;
exports.CODE_PRECONDITION_REQUIRED = 428;
exports.CODE_TOO_MANY_REQUESTS = 429;
exports.CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
exports.CODE_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
exports.CODE_INTERNAL_SERVER_ERROR = 500;
exports.CODE_NOT_IMPLEMENTED = 501;
exports.CODE_BAD_GATEWAY = 502;
exports.CODE_SERVICE_UNAVAILABLE = 503;
exports.CODE_GETWAY_TIMEOUT = 504;
exports.CODE_HTTP_VERSION_NOT_SUPPORTED = 505;
exports.CODE_VARIANT_ALSO_NEGOTIATES = 506;
exports.CODE_INSUFFICIENT_STORAGE = 507;
exports.CODE_LOOP_DETECTED = 508;
exports.CODE_NOT_EXTENDED = 509;
exports.CODE_NETWORK_AUTHENTICATION_REQUIRED = 511;




// RFC

module.exports.VALIDATE_PROVIDER_CALL="ZRFC_ER_VALIDAR_PROVEEDOR";